### PR TITLE
update sensitivity object reference

### PR DESCRIPTION
**Pull request by pet1330**
This is needed to override the default sensitivity value

### CODE REVIEW

**Comment by xon52** [comment]
I do not believe this is correct as `circle` and `marker` are the corresponding Google API objects which do not have `sensitivity` properties. `this.circle.sensitivity` returns an error.
Was there a particular problem you were trying to solve?

**Comment by pet1330** [comment]
Thanks for coming back so quickly! Sorry, that's my bad. I updated both circle and marker, but only testing marker. I was having an issue with the marker using the default sensitivity of 0.01, even when passing in a new value as a prop (for example, 1e-9 to make it more sensitive).
It seemed to work up until version ^0.3.33, but having just upgraded, it no longer works. Making the change to marker above seems to fix it, but I'm not familiar enough with TS to know why :stuck_out_tongue_closed_eyes:

**Comment by xon52** [comment]
All good. So as far as I can tell it is working as expected. I put in `:sensitivity="0.0000001"` for a marker and while zoomed in to the max, on the move event I count not not trigger the event. 
I'm not sure how you're not getting an error (but maybe without TS installed it lets you do it), but what I think your PR does is makes `sensitivity` always `null` (aka `0`). You can achieve the same result with `:sensitivity="0"`.

If you can demonstrate this not working would you be able to raise an issue for me to test?

TBH the whole sensitivity thing is a little flimsy, so would prefer not to have it; however it does cut down on a lot of events the majority don't want.

**Comment by pet1330** [comment]
Ah okay, I see what's wrong... I'm passing sensitivity as an attribute on the `options` prop rather directly as a prop to the marker. This explains why it is being ignored in place of the default value on the marker and why I can find my passed in value on the Google API object instead. I've just corrected this, and it is again working in my setup.

Thanks for the help! :smiley:

**Pull request closed without merging**
